development:
  host:localhost
  adapter: postgresql
  encoding: unicode
  database: agora_development
  pool: 5
  username: jhm
  password: Psomma1.

test:
  host:localhost
  adapter: postgresql
  encoding: unicode
  database: agora_test
  pool: 5
  username: jhm
  password: Psomma1.

production:
  host:localhost
  adapter: postgresql
  database: agora_production
  pool: 5
  timeout: 5000
